- name: Install python-pycurl and python-apt
  apt: pkg={{ item }} update_cache=yes state=present
  with_items:
   - python-pycurl
   - python-apt

- name: install curl and unzip
  apt: pkg={{item}} state=present force=yes
  with_items:
      - unzip
      - curl

- name: Add Logstash repo key
  apt_key: url="https://artifacts.elastic.co/GPG-KEY-elasticsearch" state=present

- raw: sudo apt-get install apt-transport-https

- name: Enable Logstash repository
  apt_repository: repo="deb https://artifacts.elastic.co/packages/{{logstash_version}}/apt stable main" state=present


- name: Install Logstash from repository
  apt: pkg={{item}} update_cache=yes state=present allow_unauthenticated=yes
  with_items:
   - logstash

- systemd:
    state: restarted
    enabled: yes
    daemon_reload: yes
    name: logstash
