---
- hosts: micro_appservers
  user: vagrant
  sudo: yes

  vars_files:
     - vars/default.yml

  roles:
    - hosts
    - common
    - oracle-java
    - nginx
    - rstats
    - logstash
    - microservice-appserver
    - docker
    - app-haproxy

  environment:
    "{{ (with_proxy) | ternary( proxy_env, {}) }}"   # use proxy_env only when with_proxy is true
