---
- hosts: monolitic_appservers
  user: ubuntu
  sudo: yes

  vars_files:
     - vars/default.yml

  roles:
    - hosts
    - common
    - oracle-java
    - tomcat
    - logstash
    - oldschool-appserver

  environment:
    "{{ (with_proxy) | ternary( proxy_env, {}) }}"   # use proxy_env only when with_proxy is true
