---
- hosts: elasticsearchservers
  user: vagrant
  sudo: yes

  vars_files:
     - vars/default.yml

  roles:
    - hosts
    - common
    - oracle-java
    - elasticsearch
    - apache
    - kibana
    - nagios-server
    - icinga