#! /bin/sh
PIDFILE=/var/run/cart.pid
BASE_DIRECTORY=/usr/share/shop/cart/bin

if [ `id -u` -ne 0 ]; then
    echo "You need root privileges to run this script"
    exit 1
fi

PATH=/sbin:/bin:/usr/sbin:/usr/bin:/etc/init.d
. /lib/lsb/init-functions

if [ -r /etc/default/cart ]; then
        . /etc/default/cart
        export CART_SERVICE_PROFILES
        export CART_SERVICE_PORT
        export CART_SERVICE_REDIS_URL
fi

start_service() {
        log_daemon_msg "Starting cart service"
        nohup $BASE_DIRECTORY/cart > /var/log/cart.log 2>&1 &
        echo $! > $PIDFILE
        sleep 1
        log_end_msg 0 || true
}

stop_service() {
    if [ -e $PIDFILE ]; then
        SERVICE_PID=`cat $PIDFILE|sed 's/\(.*\)pts.*/\1/g'|head -n 1`
        log_daemon_msg "Stopping cart service [$SERVICE_PID]"
        kill $SERVICE_PID
        rm $PIDFILE
        log_end_msg 0 || true
    fi
}

case "$1" in
    start)
        start_service
        ;;
    restart|reload|force-reload)
        stop_service
        sleep 1
        start_service
        ;;
    stop)
        stop_service
        ;;
    *)
        echo "Usage: $0 start|restart|stop" >&2
        exit 3
        ;;
esac