---
logstash_version : 5.x
elasticsearch_version : 5.1.2
kibana_version : 5.1.2


oracle_java_download_url : http://download.oracle.com/otn-pub/java/jdk/8u25-b17/jdk-8u25-linux-x64.tar.gz
oracle_java_zip_file : /tmp/jdk-8u25-linux-x64.tar.gz
oracle_java_folder : jdk1.8.0_25

nodejs_npm_registry : http://registry.npmjs.org/

# Comment this section when pipeline does NOT run behind web proxy
with_proxy: true
http_proxy_host: web-proxy.corp.hpecorp.net
http_proxy_port: 8080
no_proxy: localhost,127.0.0.1,.hpecorp.net,ci-repo,monitoring-node,app-server-node-1,app-server-node-2,app-server-node-3,app-server-node-4,ci-node,mongodb-node,.microservice.io,.monolith.io,test.monolith.io,shop.monolith.io

proxy_env:
  http_proxy: "http://{{http_proxy_host}}:{{http_proxy_port}}"
  no_proxy: "{{no_proxy}}"
