#!/bin/sh
set -e

rm -f /etc/nginx/sites-enabled/registration.microservice.io
if test "$1" = configure
then
   ln -sf /etc/nginx/sites-available/registration.microservice.io /etc/nginx/sites-enabled/registration.microservice.io
fi

nginx -t
systemctl daemon-reload
service nginx restart
