---
- file:
    state: directory
    dest: /etc/haproxy

- name: Identifying LB nodes
  shell: 'grep "app-server-node-[45]\( .*\|\)$" /etc/hosts'
  register: lb_nodes

- name: set haproxy.cfg
  template:
    src: haproxy.cfg.j2
    dest: /etc/haproxy/haproxy.cfg
  with_items: lb_nodes

- set_fact: "etc_hosts={% macro host_entry(lines) -%}{%- for node in lines %}{{ '\"%s\": \"%s\"\n' | format(node.split()[1], node.split()[0]) }}{%- endfor %}{%- endmacro %}{{ \"{ %s }\" | format(host_entry(lb_nodes.stdout_lines).strip().replace(\"\n\", \", \")) | from_json }}"

- name: Start haproxy container
  become: yes
  docker_container:
    name: haproxy
    restart_policy: always
    image: haproxy:alpine
    published_ports:
    - "8080:80"
    volumes:
    - "/etc/haproxy/haproxy.cfg:/usr/local/etc/haproxy/haproxy.cfg"
    etc_hosts: "{{etc_hosts}}"
